# rustdoc-md Package
#
# This module builds the rustdoc-md tool from source using Nix's Rust packaging
# infrastructure. rustdoc-md is NOT available in nixpkgs, so we need to build it
# ourselves.
#
# WHAT IS rustdoc-md?
# rustdoc-md converts Rust documentation JSON output (generated by `rustdoc --output-format json`)
# into clean, organized Markdown files. This makes Rust API documentation readable by humans
# and LLMs without needing special tooling.
#
# WHY BUILD FROM SOURCE?
# - rustdoc-md is not in nixpkgs (the main Nix package repository)
# - Building from crates.io ensures we get the exact version we want
# - Nix's build system guarantees reproducibility
#
# HOW IT WORKS:
# 1. We fetch the source tarball from crates.io using fetchurl
# 2. We use rustPlatform.buildRustPackage to build it like any other Rust project
# 3. The result is a derivation containing the rustdoc-md binary
#
# USAGE:
# In a processor that needs rustdoc-md:
#   let
#     rustdocMdPkg = import ../packages/rustdoc-md.nix { inherit pkgs; };
#   in
#   nativeBuildInputs = [ rustdocMdPkg ];
#
# Then in your buildScript:
#   rustdoc-md --path input.json --output docs.md

{ pkgs }:

# buildRustPackage is Nix's helper for building Rust projects
# It handles cargo, rustc, and all the build steps automatically
pkgs.rustPlatform.buildRustPackage rec {
  # "pname" stands for "package name" - the human-readable identifier
  pname = "rustdoc-md";

  # Version 0.2.0 is the latest as of December 2025
  # This version supports rustdoc JSON format version 42
  version = "0.2.0";

  # Fetch the source code from crates.io
  # crates.io packages all Rust crates as .tar.gz archives
  # We use fetchzip which automatically extracts the archive
  src = pkgs.fetchzip {
    # The URL pattern for crates.io downloads
    url = "https://crates.io/api/v1/crates/${pname}/${version}/download";

    # Tell fetchzip this is a gzipped tarball (crates.io uses .tar.gz)
    extension = "tar.gz";

    # SHA256 hash ensures we get exactly the code we expect
    # If the tarball changes, the build will fail (reproducibility!)
    # Note: fetchzip hashes the *extracted* contents, not the archive itself
    hash = "sha256-Gk3T3uMMN80tpSFgLfeXyarZTJI7c+iw/Jv3YLFDfYQ=";
  };

  # cargoHash is the hash of all the dependencies listed in Cargo.lock
  # This ensures that cargo downloads the exact same dependencies every time
  # If this hash is wrong, Nix will tell you the correct value
  cargoHash = "sha256-lk8nFoSqIfRnk1zFcTL6EbmTOpGExt6g0rgcYEvNL2M=";

  # doCheck = false disables running `cargo test` during the build
  # We disable tests because:
  # 1. Tests might require network access (not allowed in Nix builds)
  # 2. Tests might require a Rust nightly toolchain
  # 3. We trust the upstream maintainer's CI testing
  doCheck = false;

  # Metadata about this package for Nix tooling
  meta = with pkgs.lib; {
    description = "Convert Rust documentation JSON into clean, organized Markdown files";
    homepage = "https://github.com/tqwewe/rustdoc-md";
    license = with licenses; [ mit asl20 ];  # MIT OR Apache-2.0
    # This tool runs on Linux and macOS (anywhere Rust runs)
    platforms = platforms.unix;
  };
}
